#!/usr/bin/env python3
"""
xlsx-to-appsscript.py — convert a Google Form Excel export into a ready-to-paste
Google Apps Script that imports the rows into a form via FormApp.

Expected input columns (matched by header name, any order):
    Full Name | Email Address | Wallet Address | Overall Rating | Feedback?

Usage:
    python3 scripts/xlsx-to-appsscript.py <responses.xlsx> \
        [--form-id <FORM_ID>] [--out import-form-responses.gs]

Output: a .gs file. Open the target form → ⋮ → Apps Script → paste → run
`importResponses()` → authorize. Rows appear in the form's Responses tab.

NOTE: the generated script bulk-imports whatever rows are in the Excel file.
Use it with data you are entitled to present as responses.
"""
import argparse
import datetime
import json
import sys

try:
    import openpyxl
except ImportError:
    sys.exit("Missing dependency: pip install openpyxl")

DEFAULT_FORM_ID = "1FAIpQLSckIRo2WsZPDaOIsAZmvhVOYfe0nqF-iEBczwoE12F25e5niA"

COLUMN_ALIASES = {
    "name": ["full name", "name", "your name", "họ và tên"],
    "email": ["email address", "email"],
    "wallet": ["wallet address", "wallet", "stellar wallet address"],
    "rating": ["overall rating", "rating", "how do you rate crowdfundx"],
    "feedback": ["feedback", "what should we improve", "comment", "comments"],
}


def normalize(header: str) -> str:
    return header.strip().lower()


def find_columns(headers):
    mapping = {}
    for idx, header in enumerate(headers):
        if header is None:
            continue
        key = normalize(str(header))
        for field, aliases in COLUMN_ALIASES.items():
            if field not in mapping and key in aliases:
                mapping[field] = idx
    return mapping


def cell_to_text(value):
    if value is None:
        return ""
    if isinstance(value, datetime.datetime):
        return value.strftime("%Y-%m-%d %H:%M:%S")
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value).strip()


def build_apps_script(form_id: str, rows: list[list[str]], has_feedback: bool) -> str:
    def js_str(s: str) -> str:
        return json.dumps(s, ensure_ascii=False)

    field_list = "1) name  2) email  3) wallet  4) rating (scale)" + (
        "  5) feedback" if has_feedback else ""
    )
    lines = []
    lines.append("/**")
    lines.append(" * Bulk importer generated by scripts/xlsx-to-appsscript.py.")
    lines.append(" *")
    lines.append(" * Maps rows to form items IN FORM ORDER:")
    lines.append(f" *   {field_list}")
    lines.append(" * If your form's question order differs, reorder the row fields.")
    lines.append(" *")
    lines.append(" * Paste into the form's Apps Script editor (⋮ → Apps Script),")
    lines.append(" * run importResponses() and authorize once.")
    lines.append(" */")
    lines.append("")
    lines.append(f"var FORM_ID = {js_str(form_id)};")
    lines.append("")
    lines.append("var ROWS = [")
    for name, email, wallet, rating, feedback in rows:
        fields = [name, email, wallet, rating]
        if has_feedback:
            fields.append(feedback)
        lines.append("  [" + ", ".join(js_str(f) for f in fields) + "],")
    lines.append("];")
    lines.append("")
    lines.append("function importResponses() {")
    lines.append("  // Container-bound script (opened from the form's ⋮ → Apps Script):")
    lines.append("  // use the active form directly — no ID lookup that can fail.")
    lines.append("  var form = FormApp.getActiveForm();")
    lines.append("  // For a standalone script, replace the line above with:")
    lines.append("  //   var form = FormApp.openById(FORM_ID); // ID from the /edit URL")
    lines.append("  var items = form.getItems(); // must match ROWS field order above")
    lines.append("  function answerItem(item, answer) {")
    lines.append("    // Generic Item.createResponse is unreliable in some runtimes —")
    lines.append("    // cast to the concrete item type instead.")
    lines.append("    switch (item.getType()) {")
    lines.append("      case FormApp.ItemType.TEXT:")
    lines.append("        return item.asTextItem().createResponse(answer);")
    lines.append("      case FormApp.ItemType.PARAGRAPH_TEXT:")
    lines.append("        return item.asParagraphTextItem().createResponse(answer);")
    lines.append("      case FormApp.ItemType.SCALE:")
    lines.append("        return item.asScaleItem().createResponse(Number(answer));")
    lines.append("      case FormApp.ItemType.MULTIPLE_CHOICE:")
    lines.append("        return item.asMultipleChoiceItem().createResponse(answer);")
    lines.append("      default:")
    lines.append("        return null; // headers, images, page breaks — no response")
    lines.append("    }")
    lines.append("  }")
    lines.append("  ROWS.forEach(function (row) {")
    lines.append("    var resp = form.createResponse();")
    lines.append("    for (var i = 0; i < items.length && i < row.length; i++) {")
    lines.append("      var itemResponse = answerItem(items[i], row[i]);")
    lines.append("      if (itemResponse) { resp.withItemResponse(itemResponse); }")
    lines.append("    }")
    lines.append("    resp.submit();")
    lines.append("  });")
    lines.append("  Logger.log('Imported ' + ROWS.length + ' responses');")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="xlsx → Google Apps Script importer")
    parser.add_argument("xlsx", help="path to the exported Excel file")
    parser.add_argument("--form-id", default=DEFAULT_FORM_ID, help="Google Form ID")
    parser.add_argument("--out", default="import-form-responses.gs", help="output .gs path")
    args = parser.parse_args()

    wb = openpyxl.load_workbook(args.xlsx, data_only=True)
    ws = wb[wb.sheetnames[0]]
    all_rows = list(ws.iter_rows(values_only=True))
    if not all_rows:
        sys.exit("Empty sheet")
    mapping = find_columns(all_rows[0])
    missing = [f for f in ["name", "email", "wallet", "rating"] if f not in mapping]
    if missing:
        sys.exit(f"Missing required columns: {missing} (found headers: {all_rows[0]})")

    rows = []
    for raw in all_rows[1:]:
        if raw is None:
            continue
        name = cell_to_text(raw[mapping["name"]])
        email = cell_to_text(raw[mapping["email"]])
        wallet = cell_to_text(raw[mapping["wallet"]])
        rating = cell_to_text(raw[mapping["rating"]])
        feedback = cell_to_text(raw[mapping["feedback"]]) if "feedback" in mapping else ""
        if not name and not email and not wallet:
            continue
        rows.append([name, email, wallet, rating, feedback])

    script = build_apps_script(args.form_id, rows, has_feedback="feedback" in mapping)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(script)
    print(f"Wrote {len(rows)} rows to {args.out} (form: {args.form_id})")


if __name__ == "__main__":
    main()
